services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: application
    container_name: slack-api-app
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel-network
  db:
    container_name: slack-api-db
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: slack-api-db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    volumes:
      - ./docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-network
    
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
networks:
  laravel-network:
    driver: bridge